git:
  diffRenderers:
    - command: delta --paging=never --line-numbers
      colorArg: always
    - command: difft --color=always --display=inline --context=10
      type: extDiff
os:
  editPreset: 'helix (hx)'
  openLink: ^open {{link}}
