#!/bin/sh

# Background wallpapers
swaybg -o DP-1 -i /home/nathan/Pictures/wallpapers/gruvmoon.png &
swaybg -o DP-3 -i /home/nathan/Pictures/wallpapers/gruvmoon.png -m fill &

# Pipewire
pipewire &

# XFCE polkit
/usr/libexec/xfce-polkit &

# XFsettingsd
# 
# Unfortunately this uses xfce settings for wayland display config,
# even though at this time I would rather use kanshi
#
# I still need this for some panel functionality
xfsettingsd &

# xfce notifications, works perfectly
/usr/lib64/xfce4/notifyd/xfce4-notifyd &

# XFCE Panel
xfce4-panel &

# audio idle inhibit (blocks loginctl suspend when audio is playing)
sway-audio-idle-inhibit &

# swaylock until xfce power manager has better wayland support
swayidle -w timeout 600 'loginctl suspend' &

# start discord (give pipewire time to start)
sleep 5 && /usr/bin/flatpak run --branch=stable --arch=x86_64 \
  --command=com.discordapp.Discord \
  --file-forwarding com.discordapp.Discord

# apply openrgb profile
# /home/nathan/openrgb/OpenRGB-x86_64.AppImage --profile noram

