#!/bin/sh

# Kanshi for display mode and position configuration
kanshi &

# Background wallpapers
swaybg -o DP-1 -i "$HOME/Pictures/wallpapers/gruvmoon.png" &
swaybg -o DP-2 -i "$HOME/Pictures/wallpapers/gruvmoon.png" -m fill &

# Pipewire
pipewire &

# XFCE polkit
/usr/libexec/xfce-polkit &

# Ironbar
ironbar &

# SwayNotificationCenter
swaync &

# nm-applet
nm-applet &

# swaylock until xfce power manager has better wayland support
swayidle -w timeout 900 'loginctl suspend' before-sleep 'true' &

# run the after resume script now
# to run on resume it must also be called as 'nathan' via /etc/elogind/system-sleep/post-sleep.sh (if [ "$1" = "post" ], see loginctl(1))
"$HOME/scripts/post-suspend.sh"

# sleep before starting applications (mostly for pipewire to finish starting)
# (there is definitely a better solution for this)
sleep 3

# blueman applet
blueman-applet &

# start discord
/usr/bin/flatpak run --branch=stable --arch=x86_64 \
  --command=com.discordapp.Discord \
  --file-forwarding com.discordapp.Discord &

# start matrix clients
# /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=neochat --file-forwarding org.kde.neochat &
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/element --file-forwarding im.riot.Riot &

# audio idle inhibit (blocks loginctl suspend when audio is playing)
# points to a script that just runs sway-audio-idle-inhibit in a loop in case
# it crashes
"$HOME/scripts/saii.sh" &
