#!/bin/bash

# Shutdown daemons
pgrep -f kanshi | xargs kill &>/dev/null
pgrep -f swaybg | xargs kill &>/dev/null
pgrep -f pipewire | xargs kill &>/dev/null
pgrep -f xfce-polkit | xargs kill &>/dev/null
pgrep -f nm-applet | xargs kill &>/dev/null
pgrep -f swayidle | xargs kill &>/dev/null
pgrep -i sway-audio-idle | xargs kill &>/dev/null
pgrep -i saii | xargs kill &>/dev/null

# Sometimes appimages don't fully quit
pgrep -i AppRun | xargs kill &>/dev/null
