[language-server.lemminx]
command = "lemminx"

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[[language]]
name = "xml"
language-servers = ["lemminx"]
auto-format = true

[[language]]
name = "python"
language-servers = [ "basedpyright", "ruff" ]

[[language]]
name = "svelte"
language-servers = [ "vscode-eslint-language-server", "svelteserver" ]
formatter = { command = "prettier", args = ['--parser', 'svelte'] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [ "vscode-eslint-language-server", "typescript-language-server" ]
formatter = { command = "prettier", args = ['--parser', 'typescript'] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [ "vscode-eslint-language-server", "typescript-language-server" ]
formatter = { command = "prettier", args = ['--parser', 'typescript'] }
auto-format = true

[[language]]
name = "json"
formatter = { command = "prettier", args = ['--parser', 'json'] }
auto-format = true

[[language]]
name = "html"
formatter = { command = "prettier", args = ['--parser', 'html'] }
auto-format = true
