#!/bin/sh

# Background wallpapers
swaybg -o eDP-1 -m fill -i /home/nathan/Pictures/wallpapers/gruvmoon.png &

# Pipewire
pipewire &

# XFCE polkit
/usr/libexec/xfce-polkit &

# XFsettingsd
# 
# Unfortunately this uses xfce settings for wayland display config,
# even though at this time I would rather use kanshi
#
# I still need this for some panel functionality
xfsettingsd &

# xfce notifications, works perfectly
/usr/lib64/xfce4/notifyd/xfce4-notifyd &

# XFCE Panel
xfce4-panel &

# nm-applet
nm-applet &

# sleep before starting applications (mostly for pipewire to finish starting)
# (there is definitely a better solution for this)
sleep 5

# blueman applet
blueman-applet &

# start discord
# /usr/bin/flatpak run --branch=stable --arch=x86_64 \
#   --command=com.discordapp.Discord \
#   --file-forwarding com.discordapp.Discord &

# # start neochat
# /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=neochat --file-forwarding org.kde.neochat &

