context.modules = [
  {   name = libpipewire-module-loopback
      args = {
          node.description = "Fake Loopback Device"
          audio.position = [ FL FR ]
          capture.props = {
              media.class = "Audio/Sink"
              node.name = "pw_loopback_sink"
              node.description = "PW Loopback Sink"
          }
          playback.props = {
              media.class = "Audio/Source"
              node.name = "pw_loopback_source"
              node.description = "PW Loopback Source"
          }
      }
  }
]
